### ISSUE TITLE
Question: Normal duration to run the convert_bam_for_methylation.py

### ISSUE THREAD

**Issue by ChloeDG** [isaclee/nanopore-methylation-utilities#1]
Hi there, 
I am trying to convert a bam using the "convert_bam_for_methylation.py" and it is taking forever, for a pretty small sorted.bam (100MB). I was just wondering how long it usually takes to run this pipeline? It has been about 6h now; I haven't gotten any errors, but, it is hanging on the options: 

I first converted the methylation_calls.tsv to a bed file.
```
$./mtsv2bedGraph.py -i /home/hh/Documents/20191105_Nanopolish/barcode10/methylation_calls.tsv -g /home/hh/Documents/refs/hg38.fasta |\
  sort -k1,1 -k2,2n | bgzip > /home/hh/Documents/20191105_Nanopolish/methylation.bed.gz
tabix -p bed /home/hh/Documents/20191105_Nanopolish/methylation.bed.gz
```

Then used this bed file along with the sorted.bam to convert it. But it is just hanging here using lots of CPU. 
```
 $./convert_bam_for_methylation.py -b /home/hh/Documents/20191105_Nanopolish/barcode10/BAM/20191105.sorted.bam -c /home/hh/Documents/20191105_Nanopolish/barcode10/methylation.bed.gz -f /home/hh/Documents/refs/hg38.fasta | samtools sort -o /home/hh/Documents/20191105_Nanopolish/converted.bam



Usage:   samtools sort [options] <in.bam> <out.prefix>

Options: -n        sort by read name
         -f        use <out.prefix> as full file name instead of prefix
         -o        final output to stdout
         -l INT    compression level, from 0 to 9 [-1]
         -@ INT    number of sorting and compression threads [1]
         -m INT    max memory per thread; suffix K/M/G recognized [768M]

```
Is there something that I have missed? 

Ubuntu 16.04
16 GB Memory

Thanks in advance:-)

**Comment by isaclee** [comment]
Hello,

Which version of samtools are you using?
In the recent versions, the syntax for samtools sort has changed, and that
command works on the recent versions of samtools.
Can you update samtools and see if that works?
Also, if you are interested in one or a set of regions, providing the bed
file of the regions you are interested in does help with the speed.
Currently, if you don't provide the regions, it scans the entire genome,
which does add significant amount of time.
I do need to fix this, but I haven't had the chance to do so yet.

Let me know if samtools update fixes it, and if you have any more questions.
Thank you!

Isac

**Comment by ChloeDG** [comment]
I updated samtools and it looks like its working. I will try first to convert everything and then specific regions. 
Thank you so much for your help!

**Comment by ChloeDG** [comment]
FYI it is working great now. Super useful tool, thanks for sharing.
